---
sudo: required
language: python
services: docker

env:
  - version=">=2.6,<2.7" distro="centos-6"
  - version="" distro="centos-6"
  - version="devel" distro="centos-6"
  - version=">=2.6,<2.7" distro="centos-latest"
  - version="" distro="centos-latest"
  - version="devel" distro="centos-latest"

matrix:
  allow_failures:
    - env: version="devel" distro="centos-6"
    - env: version="devel" distro="centos-latest"

cache:
  - pip

install:
  - pip install --upgrade pip
  - if [ "${version}" != "devel" ] ; then pip install ansible"${version}" ; fi
  - if [ "${version}" = "devel" ] ; then pip install git+https://github.com/ansible/ansible.git@devel ; fi
  - pip install molecule
  - pip install docker

script:
  - if [ "${expectation}" = "fail" ] ; then ! molecule test --scenario-name "${distro}" ; else molecule test --scenario-name "${distro}" ; fi

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: "Szd6ZwX453lsQSACEHEK0augoiLnayHMGj2iTnzR5WkZFUulkkNuvfuMAsRNYIn4v3pni8V9YXz8WSb3xRMdSo7pRKSRXveu7S4WAzuYZkWo0VGJxlS6tiDlJCjyugxFbHKQGzlN8HO0AsxqMhbjYFa4bfZSdoAz2jYmOcaQkpP+uJ1HxBelT/i/tPiWZby3f4cu/7tfDV3x4wz64blWj5pGiviS6h00bsERV59cEnhH8IuvEZz+O/fKhjU7lchJiEnCaMA+nHNEHZooD7jNwqrr5SaUAdKuUBaSe7YWbr/oeJp4QbdI2Isr0C++omuKiIi4b89zxmbzp/M9Z4Kc66Lj+owHgCQ6IdvnIp/6ICDZ9IvTd5qJB8ctEsCJ/eQTkw3fIn0zidC3HUhoi+NtqbqKub81yOxFbktR1HjOSPs+oCxRX21Jxgr2b68swD4JjORuOzFSsL/euP+UUJp1fFIz7Imxr6Q84EbOGxo9kcrAyUfa78MeuJnGC9tVOP+n6w7wxqVNqjxQbBQDc1w7kgg+I1CMTVLdppZp2vI6gTnAmlRF0CWubcpIYzzuEbyVeu49+Q5jWqm6CNS9beVXu7RotulijV8IqwxXPkOclfVi9FOL8cWt1mswIQ+kW79rmGQAuwu6+LTotDakXSRUD9HFSjHKkX7sZmB+UseRuvg="
  email: false
