---
# tasks file for epel
- name: install epel-release
  package:
    name: epel-release
    state: present
  when:
    - ansible_os_family == "RedHat"
  register: epel_install_epel_release
  until: epel_install_epel_release is succeeded
  retries: 3
