---
# tasks file for epel
- name: install epel-release
  package:
    name: "{{ epel_url }}"
    state: present
  when:
    - ansible_distribution in [ "CentOS", "Red Hat Enterprise Linux" ]
  register: epel_install_epel_release
  until: epel_install_epel_release is succeeded
  retries: 3
