---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: epel-debian
    box: debian/stretch64
  - name: epel-fedora
    box: fedora/30-cloud-base
provisioner:
  name: ansible
  inventory:
    host_vars:
      epel-fedora:
        ansible_python_interpreter: /usr/bin/python3
  config_options:
    defaults:
      stdout_callback: yaml
      bin_ansible_callbacks: true
scenario:
  name: vagrant
