---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: epel-centos-6
    image: centos:6
  - name: epel-centos-latest
    image: centos:latest
provisioner:
  name: ansible
  inventory:
    host_vars:
      epel-fedora-latest:
        ansible_python_interpreter: /usr/bin/python3
      epel-fedora-rawhide:
        ansible_python_interpreter: /usr/bin/python3
  config_options:
    defaults:
      stdout_callback: yaml
      bin_ansible_callbacks: true
scenario:
  name: default
